[global]
showWarningOnDirectExecution = true

[logger]
level = "info"

[runner]
magicEnabled = true

[server]
headless = true
liveSave = false
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
